# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <epsms at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# root/inventory/createTables.sql

CREATE TABLE IF NOT EXISTS Server (
  Name varchar(100) NOT NULL,
  ShortName varchar(100) NOT NULL,
  Domain varchar(50) NOT NULL,
  IP varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Node Boolean DEFAULT 0,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (IP),
  KEY (Init),
  KEY (End),
  KEY (Checked),
  PRIMARY KEY(Name, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS HardwareType (
  Name varchar(25) NOT NULL,
  Descrip varchar(255) NOT NULL,
  Auto Boolean DEFAULT 0,
  PRIMARY KEY (Name)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SoftwareType (
  Name varchar(25) NOT NULL,
  Descrip varchar(255) NOT NULL,
  Auto Boolean DEFAULT 0,
  PRIMARY KEY (Name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Hardware (
  HardType varchar(25) NOT NULL,
  Name varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Value varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (HardType),
  KEY (Name),
  KEY (Server),
  KEY (Value),
  KEY (Init),
  KEY (End),
  KEY (Checked),
  PRIMARY KEY (HardType, Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Software (
  SoftType varchar(25) NOT NULL,
  Name varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Value varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (SoftType),
  KEY (Server),
  KEY (Value),
  KEY (Init),
  KEY (End),
  KEY (Checked),
  PRIMARY KEY (SoftType, Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
   
CREATE TABLE IF NOT EXISTS Interface (
  Name varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Address varchar(15),
  NameDNS varchar(100),
  Network varchar(15),
  Netmask varchar(15),
  MAC varchar(17),
  Type varchar(30),
  Module varchar(50),
  Active Boolean DEFAULT 1,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (Address), 
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Route (
  Num int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  Destination varchar(100) NOT NULL,
  Mask varchar(100) NOT NULL,
  Gateway varchar(100) NOT NULL,
  Flags varchar(20) NOT NULL,
  Interface varchar(30) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Num),
  KEY (Server),
  KEY (Destination),
  KEY (Mask),
  KEY (Gateway),
  KEY (Flags),
  KEY (Interface),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Num, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Protocol (
  Name varchar(20) NOT NULL,
  Descrip varchar(100) NOT NULL,
  Auto Boolean DEFAULT 0,
  PRIMARY KEY(Name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Port (
  Port int(5) NOT NULL,
  Protocol varchar(20) NOT NULL,
  Descrip varchar(255) NOT NULL,
  Auto Boolean DEFAULT 0,
  PRIMARY KEY (Port,Protocol)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ServerPort (
  Port int(5) NOT NULL,
  Protocol varchar(20) NOT NULL,
  Server varchar(100) NOT NULL,
  Process varchar(100) NOT NULL,
  IP4 Boolean DEFAULT 0,
  BindIP4 varchar(100) NULL,
  IP6 Boolean DEFAULT 0,
  BindIP6 varchar(100) NULL,
  Access varchar(3) DEFAULT "OUT", 
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Port),
  KEY (Protocol),
  KEY (Server),
  KEY (Init),
  KEY (End),
  KEY (Checked), 
  PRIMARY KEY (Port, Protocol, Server, Access, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS FileSystem (
  Name varchar(60) NOT NULL,
  Server varchar(100) NOT NULL,
  Type varchar(50) NOT NULL,
  Mount varchar(120) NOT NULL,
  Options varchar(255) NOT NULL,
  Size varchar(20) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (Type),
  KEY (Mount),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Type, Mount, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Device (
  Name varchar(60) NOT NULL,
  Server varchar(100) NOT NULL,
  Model varchar(100) NOT NULL,
  Host varchar(255) NOT NULL,
  Scheduler varchar(30) NOT NULL,
  Size varchar(20) NOT NULL,
  Vendor varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (Size),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Partition (
  Name varchar(60) NOT NULL,
  Device varchar(60) NOT NULL,
  Server varchar(100) NOT NULL,
  Size varchar(20) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Device),
  KEY (Server),
  KEY (Size),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Package (
  Name varchar(100) NOT NULL,
  Version varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Size varchar(20) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Version),
  KEY (Server),
  KEY (Size),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Version, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Exe (
  Name varchar(180) NOT NULL,
  Package varchar(160) NOT NULL,
  Server varchar(100) NOT NULL,
  FileSize varchar(20) NOT NULL,
  FileUser varchar(30) NOT NULL,
  FileGroup varchar(30) NOT NULL,
  FilePerms varchar(12) NOT NULL,
  Signature varchar(50) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Package),
  KEY (FileSize),
  KEY (FileUser),
  KEY (FileGroup),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Signature, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Connector (
  Handle varchar(30) NOT NULL,
  Server varchar(100) NOT NULL,
  IntDesignator varchar(60) NOT NULL,
  IntType varchar(60) NOT NULL,
  ExtDesignator varchar(60) NOT NULL,
  ExtType varchar(60) NOT NULL,
  PortType varchar(60) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Handle),
  KEY (IntDesignator),
  KEY (IntType),
  KEY (ExtDesignator),
  KEY (ExtType),
  KEY (PortType),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Handle, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Slot (
  Handle varchar(30) NOT NULL,
  Server varchar(100) NOT NULL,
  Designation varchar(60) NOT NULL,
  SlotType varchar(60) NOT NULL,
  SlotBusWidth varchar(60) NOT NULL,
  CurrentUsage varchar(60) NOT NULL,
  SlotLength varchar(60) NOT NULL,
  SlotId varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Handle),
  KEY (Designation),
  KEY (SlotType),
  KEY (SlotBusWidth),
  KEY (SlotLength),
  KEY (SlotId),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Handle, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Cache (
  Handle varchar(30) NOT NULL,
  Server varchar(100) NOT NULL,
  Designation varchar(60) NOT NULL,
  Level varchar(10) NOT NULL,
  Enabled varchar(10) NOT NULL,
  Mode varchar(60) NOT NULL,
  Location varchar(60) NOT NULL,
  InstSize varchar(60) NOT NULL,
  MaxSize varchar(60) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Handle),
  KEY (Designation),
  KEY (Mode),
  KEY (InstSize),
  KEY (MaxSize),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Handle, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS MemoryArray (
  Handle varchar(30) NOT NULL,
  Server varchar(100) NOT NULL,
  Location varchar(100) NOT NULL,
  MemoryUse varchar(100) NOT NULL,
  ErrorCorrectionType varchar(60) NOT NULL,
  MaxCapacity varchar(60) NOT NULL,
  NumberDevices varchar(30) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Handle),
  KEY (Server),
  KEY (Location),
  KEY (MemoryUse),
  KEY (MaxCapacity),
  KEY (NumberDevices),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Handle, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Memory (
  Handle varchar(30) NOT NULL,
  Server varchar(100) NOT NULL,
  Array varchar(30) NOT NULL,
  Locator varchar(30) NOT NULL,
  BankLocator varchar(60) NOT NULL,
  Size varchar(60) NOT NULL,
  Speed varchar(60) NOT NULL,
  Type varchar(60) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Handle),
  KEY (Server),
  KEY (Array),
  KEY (Locator),
  KEY (BankLocator),
  KEY (Size),
  KEY (Speed),
  KEY (Type),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Handle, Server, Array, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Bios (
  Characteristic varchar(150) NOT NULL,
  Server varchar(100) NOT NULL,
  Value varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Characteristic),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Characteristic, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Processor (
  Socket varchar(60) NOT NULL,
  Server varchar(100) NOT NULL,
  Type varchar(100) NOT NULL,
  Family varchar(100) NOT NULL,
  Vendor varchar(100) NOT NULL,
  Signature varchar(60) NOT NULL,
  ID varchar(60) NOT NULL,
  Version varchar(60) NOT NULL,
  Voltage varchar(60) NOT NULL,
  ExternalClock varchar(60) NOT NULL,
  MaxSpeed varchar(60) NOT NULL,
  CurrentSpeed varchar(60) NOT NULL,
  Status varchar(60) NOT NULL,
  Upgrade varchar(60) NOT NULL,
  L1Cache varchar(60) NOT NULL,
  L2Cache varchar(60) NOT NULL,
  L3Cache varchar(60) NOT NULL,
  SerialNumber varchar(60) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Socket),
  KEY (Server),
  KEY (Type),
  KEY (Family),
  KEY (Vendor),
  KEY (MaxSpeed),
  KEY (CurrentSpeed),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Socket, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ProcessorFlag (
  Flag varchar(150) NOT NULL,
  Socket varchar(60) NOT NULL,
  Server varchar(100) NOT NULL,
  Value varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Flag),
  KEY (Socket),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Flag, Socket, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Baseboard (
  Handle varchar(30) NOT NULL,
  Server varchar(100) NOT NULL,
  Manufacturer varchar(100) NOT NULL,
  ProductName varchar(100) NOT NULL,
  Version varchar(60) NOT NULL,
  SerialNumber varchar(60) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Handle),
  KEY (Server),
  KEY (Manufacturer),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Handle, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BaseboardDevice (
  Handle varchar(30) NOT NULL,
  Server varchar(100) NOT NULL,
  Type varchar(60) NOT NULL,
  Description varchar(255) NOT NULL,
  Enabled Boolean DEFAULT 1,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Handle),
  KEY (Server),
  KEY (Type),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Handle, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Module (
  Name varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  FileName varchar(255),
  Author varchar(255),
  Description varchar(255),
  License varchar(100),
  Version varchar(100),
  VerMagic varchar(100),
  SrcVersion varchar(100) NOT NULL,
  Depends varchar(255),
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (FileName),
  KEY (License),
  KEY (SrcVersion),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, SrcVersion, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS LocalUser (
  Name varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  UID int(10) NOT NULL,
  GID int(10) NOT NULL,
  PasswdType varchar(25),
  LastChange date,
  Description varchar(255),
  Home varchar(255),
  Shell varchar(255),
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (UID),
  KEY (GID),
  KEY (PasswdType),
  KEY (LastChange),
  KEY (Home),
  KEY (Shell),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS LocalGroup (
  Name varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  GID int(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (GID),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS LocalGroupUser (
  GroupName varchar(50) NOT NULL,
  UserName varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (GroupName),
  KEY (UserName),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(GroupName, UserName, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SudoDefault (
  Num int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  Rule varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Num),
  KEY (Server),
  KEY (Rule),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Num, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SudoAlias (
  TypeAlias varchar(10) NOT NULL,
  NumAlias int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  Rule varchar(2048) NOT NULL,
  Label varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (TypeAlias),
  KEY (NumAlias),
  KEY (Server),
  KEY (Label),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(TypeAlias, NumAlias, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SudoAliasItem (
  TypeAlias varchar(10) NOT NULL,
  NumAlias int(5) NOT NULL,
  NumItem int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  Item varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (TypeAlias),
  KEY (NumAlias),
  KEY (NumItem),
  KEY (Server),
  KEY (Item),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(TypeAlias, NumAlias, NumItem, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SudoUserSpec (
  Num int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  Rule varchar(2048) NOT NULL,
  UserItem varchar(255) NOT NULL,
  HostItem varchar(255) NOT NULL,
  RunasItem varchar(255) NOT NULL,
  CmndItem varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Num),
  KEY (Server),
  KEY (Rule),
  KEY (UserItem),
  KEY (HostItem),
  KEY (RunasItem),
  KEY (CmndItem),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Num, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Resolver (
  Server varchar(100) NOT NULL,
  Domain varchar(100) NOT NULL,
  Search varchar(255) NOT NULL,
  NS1 varchar(100) NOT NULL,
  NS2 varchar(100) NOT NULL,
  NS3 varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Server),
  KEY (Domain),
  KEY (Search),
  KEY (NS1),
  KEY (NS2),
  KEY (NS3),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ResolverOption (
  ROption varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (ROption),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(ROption, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS FileHost (
  NumHost int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  IP varchar(100) NOT NULL,
  Rule varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (NumHost),
  KEY (Server),
  KEY (IP),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(NumHost, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS FileHostAlias (
  NumHost int(5) NOT NULL,
  NumAlias int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  Name varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (NumHost),
  KEY (NumAlias),
  KEY (Server),
  KEY (Name),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(NumHost, NumAlias, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS IPTablesPolicy (
  IPTable varchar(20) NOT NULL,
  Chain varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Policy varchar(20) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (IPTable),
  KEY (Chain),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(IPTable, Chain, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS IPTables (
  Num int(5) NOT NULL,
  Rule varchar(255) NOT NULL,
  IPTable varchar(20) NOT NULL,
  Chain varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  InterfaceIN varchar(30),
  InterfaceOUT varchar(30),
  Source varchar(255),
  Destination varchar(255),
  Protocol varchar(20),
  SPort varchar(255),
  DPort varchar(255),
  State varchar(255),
  Jump varchar(255),
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Num),
  KEY (Rule),
  KEY (IPTable),
  KEY (Chain),
  KEY (Server),
  KEY (InterfaceIN),
  KEY (InterfaceOUT),
  KEY (Source),
  KEY (Destination),
  KEY (Protocol),
  KEY (SPort),
  KEY (DPort),
  KEY (State),
  KEY (Jump),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(IPTable, Chain, Num, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TCPWrappers (
  Type varchar(10) NOT NULL,
  Service varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Type),
  KEY (Service),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Type, Service, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TCPWrappersHost (
  Type varchar(10) NOT NULL,
  Service varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Host varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Type),
  KEY (Service),
  KEY (Server),
  KEY (Host),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Type, Service, Server, Host, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS PAMAccessModule (
  Module varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Module),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Module, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS PAMAccessRule (
  Num int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  Rule varchar(255) NOT NULL,
  Type varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Num),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Num, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS PAMAccessRuleUser (
  Num int(5) NOT NULL,
  User varchar(200) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Num),
  KEY (User),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Num, User, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS PAMAccessRuleOrigin (
  Num int(5) NOT NULL,
  Origin varchar(200) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Num),
  KEY (Origin),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Num, Origin, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Crontab (
  Num int(5) NOT NULL,
  Server varchar(100) NOT NULL,
  User varchar(50) NOT NULL,
  Minute varchar(100) NOT NULL,
  Hour varchar(100) NOT NULL,
  Day varchar(100) NOT NULL,
  Month varchar(100) NOT NULL,
  DayWeek varchar(100) NOT NULL,
  Command text NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Num),
  KEY (Server),
  KEY (User),
  KEY (Minute),
  KEY (Hour),
  KEY (Day),
  KEY (Month),
  KEY (DayWeek),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Num, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinAccount (
  Domain varchar(40) NOT NULL,
  Name varchar(75) NOT NULL,
  Server varchar(100) NOT NULL,
  SystemAccount varchar(10) NOT NULL,
  Caption varchar(200) NOT NULL,
  AccountType varchar(50) NULL,
  Disabled varchar(10) NULL,
  FullName varchar(255) NULL,
  LocalAccount varchar(10) NOT NULL,
  Lockout varchar(10) NULL,
  PasswordChangeable varchar(10) NULL,
  PasswordExpires varchar(10) NULL,
  PasswordRequired varchar(10) NULL,
  SID varchar(100) NOT NULL,
  SIDType varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Domain),
  KEY (Name),
  KEY (Server),
  KEY (SID),
  KEY (SIDType),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Domain, Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinBaseBoard (
  Tag varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  Manufacturer varchar(100) NOT NULL,
  Product varchar(100) NOT NULL,
  Model varchar(100) NOT NULL,
  Version varchar(100) NOT NULL,
  SerialNumber varchar(50) NOT NULL,
  HostingBoard varchar(10) NOT NULL,
  HotSwappable varchar(10) NOT NULL,
  PoweredOn varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Tag),
  KEY (Server),
  KEY (Manufacturer),
  KEY (Model),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Tag, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinBios (
  Name varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(255) NOT NULL,
  SoftwareElementID varchar(100) NOT NULL,
  SoftwareElementState varchar(20) NOT NULL,
  TargetOperatingSystem varchar(50) NOT NULL,
  Version varchar(64) NOT NULL,
  BuildNumber varchar(50) NOT NULL,
  CodeSet varchar(64) NOT NULL,
  CurrentLanguage varchar(20) NOT NULL,
  IdentificationCode varchar(64) NOT NULL,
  LanguageEdition varchar(32) NOT NULL,
  Manufacturer varchar(100) NOT NULL,
  PrimaryBIOS varchar(10) NOT NULL,
  ReleaseDate varchar(40) NOT NULL,
  SerialNumber varchar(50) NOT NULL,
  Status varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (Caption),
  KEY (SoftwareElementID),
  KEY (Manufacturer),
  KEY (ReleaseDate),
  KEY (Status),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinBiosChar (
  Name varchar(100) NOT NULL,
  CharCode varchar(10) NOT NULL,
  Server varchar(100) NOT NULL,
  Description varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (CharCode),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, CharCode, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinBus (
  DeviceID varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  BusType varchar(50) NOT NULL,
  BusNum varchar(10) NOT NULL,
  Availability varchar(255) NOT NULL,
  ConfigManagerErrorCode varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (DeviceID),
  KEY (Server),
  KEY (Caption),
  KEY (BusType),
  KEY (BusNum),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(DeviceID, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinDiskDrive (
  DeviceID varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(255) NOT NULL,
  DiskIndex varchar(10) NOT NULL,
  InterfaceType varchar(20) NOT NULL,
  Model varchar(100) NOT NULL,
  Size varchar(20) NOT NULL,
  Availability varchar(255) NOT NULL,
  TotalHeads varchar(10) NOT NULL,
  TotalCylinders varchar(10) NOT NULL,
  TracksPerCylinder varchar(10) NOT NULL,
  TotalTracks varchar(20) NOT NULL,
  SectorsPerTrack varchar(10) NOT NULL,
  TotalSectors varchar(20) NOT NULL,
  BytesPerSector varchar(10) NOT NULL,
  DefaultBlockSize varchar(10) NOT NULL,
  MediaType varchar(50) NOT NULL,
  Partitions varchar(10) NOT NULL,
  ConfigManagerErrorCode varchar(255) NOT NULL,
  SerialNumber varchar(100) NOT NULL,
  SCSIBus varchar(10) NOT NULL,
  SCSIPort varchar(10) NOT NULL,
  SCSITargetID varchar(10) NOT NULL,
  SCSILogicalUnit varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (DeviceID),
  KEY (Server),
  KEY (InterfaceType),
  KEY (MediaType),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(DeviceID, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinDiskDrivePartition (
  DiskDeviceID varchar(100) NOT NULL,
  PartitionDeviceID varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (DiskDeviceID),
  KEY (PartitionDeviceID),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(DiskDeviceID, PartitionDeviceID, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinDiskPartition (
  DeviceID varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  DiskIndex varchar(10) NOT NULL,
  PartitionIndex varchar(10) NOT NULL,
  PartitionType varchar(50) NOT NULL,
  Size varchar(20) NOT NULL,
  BlockSize varchar(10) NOT NULL,
  NumberOfBlocks varchar(20) NOT NULL,
  Access varchar(50) NOT NULL,
  Availability varchar(255) NOT NULL,
  Bootable varchar(10) NOT NULL,
  BootPartition varchar(10) NOT NULL,
  PrimaryPartition varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (DeviceID),
  KEY (Server),
  KEY (PartitionType),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(DeviceID, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinDriver (
  Name varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(255) NOT NULL,
  ErrorControl varchar(20) NOT NULL,
  PathName varchar(255) NOT NULL,
  ServiceType varchar(30) NOT NULL,
  StartMode varchar(20) NOT NULL,
  State varchar(30) NOT NULL,
  TagId varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (Caption),
  KEY (PathName),
  KEY (ServiceType),
  KEY (StartMode),
  KEY (State),
  KEY (TagId),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinGroup (
  Domain varchar(40) NOT NULL,
  Name varchar(75) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(200) NOT NULL,
  LocalAccount varchar(10) NOT NULL,
  SID varchar(100) NOT NULL,
  SIDType varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Domain),
  KEY (Name),
  KEY (Server),
  KEY (SID),
  KEY (SIDType),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Domain, Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinGroupUser (
  GroupDomain varchar(40) NOT NULL,
  GroupName varchar(75) NOT NULL,
  UserDomain varchar(40) NOT NULL,
  UserName varchar(75) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (GroupDomain),
  KEY (GroupName),
  KEY (UserDomain),
  KEY (UserName),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(GroupDomain, GroupName, UserDomain, UserName, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinLogicalDisk (
  DeviceID varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  DriveType varchar(50) NOT NULL,
  FileSystem varchar(50) NOT NULL,
  Size varchar(20) NOT NULL,
  Access varchar(50) NOT NULL,
  Availability varchar(255) NOT NULL,
  Compressed varchar(10) NOT NULL,
  ConfigManagerErrorCode varchar(255) NOT NULL,
  SupportsDiskQuotas varchar(10) NOT NULL,
  QuotasDisabled varchar(10) NOT NULL,
  SupportsFileBasedCompression varchar(10) NOT NULL,
  VolumeName varchar(50) NOT NULL,
  VolumeSerialNumber varchar(50) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (DeviceID),
  KEY (Server),
  KEY (DriveType),
  KEY (FileSystem),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(DeviceID, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinLogicalDiskPartition (
  LogicalDiskDeviceID varchar(100) NOT NULL,
  PartitionDeviceID varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (LogicalDiskDeviceID),
  KEY (PartitionDeviceID),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(LogicalDiskDeviceID, PartitionDeviceID, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinMemory (
  Tag varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  Capacity varchar(20) NOT NULL,
  DataWidth varchar(10) NOT NULL,
  TotalWidth varchar(10) NOT NULL,
  DeviceLocator varchar(50) NOT NULL,
  FormFactor varchar(20) NOT NULL,
  HotSwappable varchar(10) NOT NULL,
  Manufacturer varchar(100) NOT NULL,
  MemoryType varchar(20) NOT NULL,
  PositionInRow varchar(10) NOT NULL,
  Speed varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Tag),
  KEY (Server),
  KEY (DeviceLocator),
  KEY (FormFactor),
  KEY (Manufacturer),
  KEY (MemoryType),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Tag, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinMemoryArray (
  Tag varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  HotSwappable varchar(10) NOT NULL,
  Location varchar(50) NOT NULL,
  MaxCapacity varchar(20) NOT NULL,
  MemoryDevices varchar(10) NOT NULL,
  MemoryErrorCorrection varchar(20) NOT NULL,
  MemoryUse varchar(20) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Tag),
  KEY (Server),
  KEY (Location),
  KEY (MemoryUse),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Tag, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinMemoryLocation (
  GroupTag varchar(100) NOT NULL,
  PartTag varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (GroupTag),
  KEY (PartTag),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(GroupTag, PartTag, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinNetworkAdapter (
  DeviceID varchar(10) NOT NULL,
  Server varchar(100) NOT NULL,
  Name varchar(100) NOT NULL,
  AdapterType varchar(50) NOT NULL,
  Manufacturer varchar(100) NOT NULL,
  MACAddress varchar(20) NOT NULL,
  Availability varchar(255) NOT NULL,
  ConfigManagerErrorCode varchar(255) NOT NULL,
  AdapterIndex varchar(10) NOT NULL,
  NetConnectionID varchar(100) NOT NULL,
  NetConnectionStatus varchar(30) NOT NULL,
  ServiceName varchar(50) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (DeviceID),
  KEY (Server),
  KEY (AdapterType),
  KEY (Manufacturer),
  KEY (MACAddress),
  KEY (NetConnectionStatus),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(DeviceID, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinNetworkAdapterConfig (
  NetIndex varchar(10) NOT NULL,
  Server varchar(100) NOT NULL,
  Description varchar(255) NOT NULL,
  IPAddress varchar(50) NOT NULL,
  IPSubnet varchar(50) NOT NULL,
  DefaultIPGateway varchar(50) NOT NULL,
  DefaultTOS varchar(10) NOT NULL,
  DefaultTTL varchar(10) NOT NULL,
  DHCPEnabled varchar(10) NOT NULL,
  DHCPServer varchar(50) NOT NULL,
  DNSDomain varchar(50) NOT NULL,
  DNSDomainSuffixSearchOrder varchar(200) NOT NULL,
  DNSEnabledForWINSResolution varchar(10) NOT NULL,
  DNSDomainSearchOrder varchar(100) NOT NULL,
  IGMPLevel varchar(50) NOT NULL,
  MACAddress varchar(20) NOT NULL,
  WINSEnableLMHostsLookup varchar(10) NOT NULL,
  WINSPrimaryServer varchar(50) NOT NULL,
  WINSSecondaryServer varchar(50) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (NetIndex),
  KEY (Server),
  KEY (IPAddress),
  KEY (IPSubnet),
  KEY (DefaultIPGateway),
  KEY (DHCPServer),
  KEY (DNSDomain),
  KEY (DNSDomainSearchOrder),
  KEY (MACAddress),
  KEY (WINSPrimaryServer),
  KEY (WINSSecondaryServer),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(NetIndex, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinNetworkAdapterSetting (
  DeviceID varchar(10) NOT NULL,
  NetIndex varchar(10) NOT NULL,
  Server varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (DeviceID),
  KEY (NetIndex),
  KEY (Server),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(DeviceID, NetIndex, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinOnBoardDevice (
  Tag varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  Description varchar(255) NOT NULL,
  DeviceType varchar(20) NOT NULL,
  Manufacturer varchar(100) NOT NULL,
  Model varchar(100) NOT NULL,
  Version varchar(100) NOT NULL,
  SerialNumber varchar(50) NOT NULL,
  Enabled varchar(10) NOT NULL,
  HotSwappable varchar(10) NOT NULL,
  PoweredOn varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Tag),
  KEY (Server),
  KEY (DeviceType),
  KEY (Manufacturer),
  KEY (Model),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Tag, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinPortConnector (
  Tag varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  ConnectorType varchar(50) NOT NULL,
  ExternalReferenceDesignator varchar(100) NOT NULL,
  InternalReferenceDesignator varchar(100) NOT NULL,
  PortType varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Tag),
  KEY (Server),
  KEY (ConnectorType),
  KEY (ExternalReferenceDesignator),
  KEY (InternalReferenceDesignator),
  KEY (PortType),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Tag, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinShare (
  Name varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  PathShare varchar(255) NOT NULL,
  TypeShare varchar(100) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (PathShare),
  KEY (TypeShare),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinPackage (
  Name varchar(100) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(100) NOT NULL,
  Description varchar(255) NOT NULL,
  InstallDate Date NOT NULL,
  InstallLocation varchar(255) NOT NULL,
  InstallState varchar(25) NOT NULL,
  Vendor varchar(100) NOT NULL,
  Version varchar(50) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (InstallDate),
  KEY (InstallState),
  KEY (Vendor),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinService (
  Name varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  Caption varchar(255) NOT NULL,
  ErrorControl varchar(20) NOT NULL,
  PathName varchar(255) NOT NULL,
  ProcessId varchar(10) NOT NULL,
  StartMode varchar(20) NOT NULL,
  State varchar(30) NOT NULL,
  TagId varchar(10) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (Name),
  KEY (Server),
  KEY (Caption),
  KEY (PathName),
  KEY (ProcessId),
  KEY (StartMode),
  KEY (State),
  KEY (TagId),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(Name, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS WinProcessor (
  DeviceID varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  Name varchar(255) NOT NULL,
  Caption varchar(255) NOT NULL,
  ConfigManagerErrorCode varchar(255) NOT NULL,
  CPUStatus varchar(50) NOT NULL,
  CurrentClockSpeed varchar(10) NOT NULL,
  DataWidth varchar(10) NOT NULL,
  Family varchar(100) NOT NULL,
  L2CacheSize varchar(10) NOT NULL,
  L2CacheSpeed varchar(10) NOT NULL,
  L3CacheSize varchar(10) NOT NULL,
  L3CacheSpeed varchar(10) NOT NULL,
  Manufacturer varchar(255) NOT NULL,
  MaxClockSpeed varchar(10) NOT NULL,
  NumberOfCores varchar(10) NOT NULL,
  NumberOfLogicalProcessors varchar(10) NOT NULL,  
  ProcessorID varchar(20) NOT NULL,
  ProcessorType varchar(30) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (DeviceID),
  KEY (Server),
  KEY (Name),
  KEY (Caption),
  KEY (CPUStatus),
  KEY (Family),
  KEY (Manufacturer),
  KEY (NumberOfCores),
  KEY (NumberOfLogicalProcessors),
  KEY (ProcessorType),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(DeviceID, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS OpenvasHost (
  ScanId varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  IP varchar(50) NOT NULL,
  StartScan DateTime NOT NULL,
  CVSS varchar(10) NOT NULL,
  Severity varchar(20) NOT NULL,
  TotalHigh varchar(10) NOT NULL,
  TotalMedium varchar(10) NOT NULL,
  TotalLow varchar(10) NOT NULL,
  TotalLog varchar(10) NOT NULL,
  TotalFalsePositive varchar(10) NOT NULL,
  ReportHTML varchar(255) NOT NULL,
  ReportPDF varchar(255) NOT NULL,
  ReportTXT varchar(255) NOT NULL,
  ReportXML varchar(255) NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (ScanId),
  KEY (Server),
  KEY (IP),
  KEY (StartScan),
  KEY (CVSS),
  KEY (Severity),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(ScanId, Server, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS OpenvasResult (
  ScanId varchar(50) NOT NULL,
  Server varchar(100) NOT NULL,
  Id int(5) NOT NULL,
  TaskId varchar(50) NOT NULL,
  TaskName varchar(255) NOT NULL,
  StartScan DateTime NOT NULL,
  ResultId varchar(50) NOT NULL,
  Port varchar(10) NOT NULL,
  Protocol varchar(20) NOT NULL,
  CVSS varchar(10) NOT NULL,
  Severity varchar(20) NOT NULL,
  NVTName varchar(255) NOT NULL,
  NVTOID varchar(255) NOT NULL,
  Summary text NOT NULL,
  SpecificResult text NOT NULL,
  Impact text NOT NULL,
  Solution text NOT NULL,
  AffectedSoftware text NOT NULL,
  VulnerabilityInsight text NOT NULL,
  DetectionMethod text NOT NULL,
  ProductDetectionResult text NOT NULL,
  BID text NOT NULL,
  CVE text NOT NULL,
  CERT text NOT NULL,
  OtherRef text NOT NULL,
  Init DateTime NOT NULL,
  End DateTime DEFAULT NULL,
  Checked DateTime DEFAULT NULL,
  Auto Boolean DEFAULT 0,
  KEY (ScanId),
  KEY (Server),
  KEY (Id),
  KEY (TaskId),
  KEY (TaskName),
  KEY (StartScan),
  KEY (ResultId),
  KEY (Port),
  KEY (Protocol),
  KEY (CVSS),
  KEY (Severity),
  KEY (NVTName),
  KEY (NVTOID),
  KEY (Init),
  KEY (End),
  PRIMARY KEY(ScanId, Server, Id, Init)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

