---
# Instalación del servidor Nagios 

- name: Be sure nagios is installed (yum)
  yum: pkg={{ item }} enablerepo={{ labelEpel }} state=installed
  with_items: "{{ packageNagios }}"
  when: ansible_pkg_mgr == "yum"

#- name: Be sure nagios is installed (apt)
#  apt: pkg={{ item }} state=installed update_cache=yes force=yes
#  with_items: "{{ packageNagios }}"
#  when: ansible_pkg_mgr == "apt"

- name: Enlazar /etc/nagios3 -> /etc/nagios (Centos)
  file: path=/etc/nagios3 state=link src=/etc/nagios force=yes
  when: ansible_os_family == "RedHat" 

- name: Enlazar /etc/init.d/nagios3 -> /etc/init.d/nagios (Centos)
  file: path=/etc/init.d/nagios3 state=link src=/etc/init.d/nagios force=yes
  when: ansible_os_family == "RedHat" 

#- name: start nagios
#  service: name=nagios3 state=started enabled=yes
