---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <epsms at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# Grafana Server Installation 

- name: Copy grafana repository to /etc/yum.repos.d 
  copy: src=etc/yum.repos.d/grafana.repo dest=/etc/yum.repos.d owner=root group=root mode=0644
  when: ansible_pkg_mgr == "yum"

- name: Be sure grafana is installed
  yum: pkg={{ item }} enablerepo=grafana state=installed update_cache=yes
  register: instGrafana
  with_items: "{{ packageGrafana }}"
  when: ansible_pkg_mgr == "yum"

- name: Active Grafana in chkconfig
  shell: (chkconfig grafana-server on) > /dev/null 2> /dev/null executable="/bin/bash"
  when: instGrafana|changed

- name: Add user to root group
  user: name=grafana groups=root
