---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <epsms at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# Grafana Server tasks 

- include: install.yml 
  tags: [ grafana, install ]
- include: openssl.yml
  tags: [ grafana, openssl ]
- include: config.yml 
  tags: [ grafana, config ]
- include: influxdb.yml 
  tags: [ grafana, influxdb ]
- include: munininfluxdb.yml
  tags: [ grafana, munininfluxdb ]
- include: graphios.yml
  tags: [ grafana, graphios ]
- include: dashboards.yml
  tags: [ grafana, dashboards ]
