---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <epsms at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# Restarts

- name: restart gsad
  service: name=gsad state=restarted enabled=yes

- name: restart openvas-manager
  service: name=openvas-manager state=restarted enabled=yes

- name: restart openvas-scanner
  service: name=openvas-scanner state=restarted enabled=yes

- name: restart apache
  service: name={{ daemonApache }} state=restarted enabled=yes
  delegate_to: "{{ hostWeb }}"

