---
# Restarts

- name: restart gsad
  service: name=gsad state=restarted enabled=yes

- name: restart openvas-manager
  service: name=openvas-manager state=restarted enabled=yes

- name: restart openvas-scanner
  service: name=openvas-scanner state=restarted enabled=yes
