---
# Apache Server Configuration

- name: Copy ansible-ssl.conf to /etc/httpd/conf.d (yum)
  template: src=etc/httpd/conf.d/ansible-ssl.conf.j2 dest=/etc/httpd/conf.d/ansible-ssl.conf owner=root group=root mode=0644
  when: ansible_pkg_mgr == "yum"

#- name: Copy ansible-ssl to /etc/apache2/sites-available (apt)
#  template: src=etc/apache2/sites-available/ansible-ssl.j2 dest=/etc/apache2/sites-available/ansible-ssl owner=root group=root mode=0644
#  when: ansible_pkg_mgr == "apt"

#- name: Enable ssl module (Debian)
#  shell: a2enmod ssl
#  when: ansible_os_family == "Debian"

- name: Be sure mod_ssl is installed (yum)
  yum: pkg=mod_ssl state=installed
  when: ansible_pkg_mgr == "yum"
 
- name: Disable port 80
  lineinfile: name={{ pathApachePorts }} state=present regexp="^#?Listen 80" line='#Listen 80' 

- name: Disable NameVirtualHost 80
  lineinfile: name={{ pathApachePorts }} state=present regexp="^#?NameVirtualHost \*:80" line='#NameVirtualHost *:80'

- name: Create user admin
  htpasswd: path={{ pathApache }}/.passwdFile name=admin password={{ passwdWebAdmin }} owner=root group={{ userApache }} mode=0640

#- name: Enable ansible-ssl in apache (Debian)
#  shell: a2ensite ansible-ssl 
#  notify: restart apache
#  when: ansible_os_family == "Debian"

#- name: Disable defaults in apache (Debian)
#  shell: a2dissite {{ item }}
#  with_items:
#    - default
#    - default-ssl
#  notify: restart apache
#  when: ansible_os_family == "Debian"

- name: Get values of ssl.conf (Centos)
  shell: (grep "^{{ item }}" {{ pathApache }}/conf.d/ssl.conf|head -1) || echo "" 2>/dev/null
  register: varSSL
  with_items:
    - SSLProtocol
    - SSLHonorCipherOrder
    - SSLCipherSuite
    - SSLProxyEngine
    - SSLCertificateFile
    - SSLCertificateKeyFile
  changed_when: False
  when: ansible_os_family == "RedHat"

- name: Comment SSL variables in ssl.conf (Centos)
  lineinfile: name={{ pathApache }}/conf.d/ssl.conf regexp="^#?{{ item.stdout }}" line='#{{ item.stdout }}'
  with_items: "{{ varSSL.results }}"
  notify: restart apache
  when: ansible_os_family == "RedHat" and item.stdout != ""

- name: Copy index.html to pathApacheHTML 
  template: src=var/www/index.html.j2 dest={{ pathApacheHTML }}/index.html owner={{ userApache }} group={{ userApache }} mode=0644

- name: Create directory help 
  file: path={{ pathApacheHTML }}/help state=directory owner={{ userApache }} group={{ userApache }} mode=0755

- name: Copy Help files to pathApacheHTML
  copy: src=var/www/help/{{ item }} dest={{ pathApacheHTML }}/help owner={{ userApache }} group={{ userApache }} mode=0644
  with_items:
    - description.txt 
    - structure.txt
    - menu.txt
    - configure.txt
    - configextra.txt
    - faq.txt
    - example.txt
    - index.html

- name: Be sure apache daemon is running and enabled
  service: name={{ daemonApache }} state=started enabled=true

