---
# Openssl Installation and SSL Cert Generation 

- name: Be sure openssl is installed (yum)
  yum: pkg={{ packageOpenssl }} state=installed
  when: ansible_pkg_mgr == "yum"

#- name: Be sure apache is installed (apt)
#  apt: pkg={{ packageOpenssl }} state=installed update_cache=yes force=yes
#  when: ansible_pkg_mgr == "apt"

- name: Create directory ssl
  file: path={{ pathApache }}/ssl state=directory owner=root group=root mode=0755

- name: Create self-signed Cert 
  shell: openssl req -new -nodes -x509 -subj "/C=ES/ST=Alicante/L=Alicante/O=IT/CN={{ ansible_fqdn }}" -days 3650 -keyout {{ pathApache }}/ssl/ansible-server.key -out {{ pathApache }}/ssl/ansible-server.crt -extensions v3_ca creates={{ pathApache }}/ssl/ansible-server.crt

- name: Config certs permissions
  file: path={{ pathApache }}/ssl/{{ item }} owner=root group=root mode=0640
  with_items:
    - ansible-server.key
    - ansible-server.crt 
