---
# Windows hosts with Inner Access
- hosts: ansible 
  remote_user: "{{ sshUserNodes }}"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - include: group_by.yml

- hosts: winNodes
  remote_user: "{{ sshUserNodes }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: False
  roles:
    - winNode 

