---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <epsms at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# Getting vulnerabilities from servers 

- include: preScan.yml
  tags: [ openvas, dataDB, preScan ]

- include: startScan.yml hostScan={{ item.item.Name }}
  tags: [ openvas, dataDB, startScan ]
  with_items: "{{ serversInventoryList.results }}"
  #when: serversInventoryList.results[0].skipped is not defined and ompStatus.stdout == "OK" and item.stdout is defined and item.stdout != ""
  when: ompStatus.stdout == "OK" and item.stdout is defined and item.stdout != ""

- include: updateWiki.yml 
  tags: [ openvas, dataDB, updateWiki ]
  when: openvas is defined

