---
# OpenVas Server Installation 

- name: Copy atomic repository to /etc/yum.repos.d 
  copy: src=etc/yum.repos.d/atomic.repo dest=/etc/yum.repos.d owner=root group=root mode=0644
  when: ansible_pkg_mgr == "yum"

- name: Copy GPG keys to /etc/pki/rpm-gpg
  copy: src=etc/pki/rpm-gpg/{{ item }} dest=/etc/pki/rpm-gpg owner=root group=root mode=0644
  with_items:
    - RPM-GPG-KEY.art.txt
    - RPM-GPG-KEY.atomicorp.txt
  when: ansible_pkg_mgr == "yum"

- name: Be sure openvas is installed
  yum: pkg={{ item }} enablerepo=atomic state=installed update_cache=yes
  with_items:
    - openvas-cli-1.3.1-6.el6.art
    - openvas-libraries-7.0.9-18.el6.art
    - openvas-manager-5.0.9-28.el6.art
    - openvas-scanner-4.0.6-19.el6.art
    - openvas-1.0-17.el6.art
    - greenbone-security-assistant-5.0.6-16.el6.art
  when: ansible_pkg_mgr == "yum"

- name: Be sure needed tools are installed
  yum: pkg=expect state=installed
  with_items:
    - expect
    - rsync
    - wget
    - cursl
    - gnupg2
    - coreutils
  when: ansible_pkg_mgr == "yum"
