---
#  Tareas Host OpenVAS Server 

- include: install.yml 
  tags: [ openvas, install ]
- include: config.yml 
  tags: [ openvas, config ]
- include: update.yml 
  tags: [ openvas, update ]
- include: dataDB.yml 
  tags: [ openvas, dataDB ]
