---
# Configuración del servidor mysql 

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user

- name: update mysql root password for all root accounts
  mysql_user: name=root host=localhost priv=*.*:ALL,GRANT password={{ passwdMysqlRoot }} state=present

- name: Copy .my.cnf file with root password credentials
  template: src=root/.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} priv=*.*:ALL,GRANT password={{ passwdMysqlRoot }} state=present
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_fqdn }}"
    - "{{ hostMysql }}"
    - localhost
    - 127.0.0.1
    - ::1
  notify: restart mysql

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
    - "{{ ansible_hostname }}"
    - "{{ ansible_fqdn }}"
    - "{{ hostMysql }}"
  notify: restart mysql

- name: Remove the test database
  mysql_db: name=test state=absent
  notify: restart mysql

- name: Create directory /var/log/ansible
  file: path=/var/log/ansible owner=root group=root mode=0755 state=directory

- name: Delete old Ansible temporary directories
  shell: ((find $HOME/.ansible/tmp/* -mtime +0 -delete) || echo "No") 2>/dev/null executable="/bin/bash"
  become: no
  changed_when: False
  ignore_errors: yes

