---
# Create inventory database 
- name: Create the inventory database
  mysql_db: name=inventory state=present

# Create inventory user (localhost, hostMysql and hostWeb access)
- name: Create inventory user
  mysql_user: name=inventory password={{ passwdMysqlInventory }} priv=inventory.*:ALL host={{ item }} state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
    - "{{ hostMysql }}"
    - "{{ hostWeb }}"

# Create inventory user (hostsAdmin access)
- name: Create inventory user
  mysql_user: name=inventory password={{ passwdMysqlInventory }} priv=inventory.*:ALL host={{ item }} state=present
  with_items: "{{ hostsAdmins }}"

# Create inventory directory
- name: Create inventory directory
  file: path={{ pathInventoryDirectory }} owner=root group=root state=directory

# Copy SQL file (tables)
- name: Copy SQL file (tables)
  copy: src=root/inventory/createTables.sql dest={{ pathInventoryDirectory }}/createTables.sql owner=root group=root mode=0600

# Create tables
- mysql_db: state=import name=inventory target={{ pathInventoryDirectory }}/createTables.sql 
