---
# Instalación del servidor mysql 

- name: Be sure mysql-server is installed (yum)
  yum: pkg={{ item }} state=installed
  with_items: "{{ packageMysql }}"
  when: ansible_pkg_mgr == "yum"

#- name: Be sure mysql-server is installed (apt)
#  apt: pkg={{ item }} state=installed update_cache=yes force=yes
#  with_items: "{{ packageMysql }}"
#  when: ansible_pkg_mgr == "apt"

- name: Configure my.cnf file (commenting bind-address = 127.0.0.1)
  lineinfile: name={{ pathMysqlConf }} state=present regexp='^bind-address\s+=\s+127.0.0.1' line='#bind-address = 127.0.0.1' backrefs=yes
  notify: restart mysql

- name: Configure my.cnf file (adding bind-address with the Mysql server IP) 
  lineinfile: name={{ pathMysqlConf }} state=present regexp='^bind-address = {{ hostMysql }}$' insertafter='\[mysqld\]' line='bind-address = {{ hostMysql }}'
  notify: restart mysql 

- name: Configure my.cnf file (adding max_connect_errors)
  lineinfile: name={{ pathMysqlConf }} state=present regexp='^max_connect_errors = 999999999$' insertafter='\[mysqld\]' line='max_connect_errors = 999999999'
  notify: restart mysql

- name: Create mysql log file (Centos)
  file: path={{ logFileMysql }} state=file owner=mysql group=mysql mode=0640
  when: ansible_os_family == "RedHat" 

- name: Configure my.cnf file (adding general_log_file)
  lineinfile: name={{ pathMysqlConf }} state=present regexp='^general_log_file = {{ logFileMysql }}$' insertafter='\[mysqld\]' line='general_log_file = {{ logFileMysql }}'
  notify: restart mysql

- name: Configure my.cnf file (adding general_log)
  lineinfile: name={{ pathMysqlConf }} state=present regexp='^general_log = 1$' insertafter='\[mysqld\]' line='general_log = 1'
  notify: restart mysql

- name: Configure /etc/hosts.allow file with hostMysql
  lineinfile: "name=/etc/hosts.allow state=present regexp='^mysqld: {{ hostMysql }}' line='mysqld: {{ hostMysql }}'"

- name: Configure /etc/hosts.allow file with hostWeb
  lineinfile: "name=/etc/hosts.allow state=present regexp='^mysqld: {{ hostWeb }}' line='mysqld: {{ hostWeb }}'"

- name: Configure /etc/hosts.allow file with hostsAdmins
  lineinfile: "name=/etc/hosts.allow state=present regexp='^mysqld: {{ item }}' line='mysqld: {{ item }}'"
  with_items: "{{ hostsAdmins }}"

- name: Be sure mysql daemon is running and enabled
  service: name={{ daemonMysql }} state=started enabled=true

