---
- hosts: newNode 
  gather_facts: True
  user: root
  vars: 
    pathAnsible: "{{ pathAnsibleValue }}"
    pathAnsibleLibrary: "{{ pathAnsibleLibraryValue }}"

  tasks:

  - name: Enlazar /[pathAnsibleLibrary]/path_facts -> /[pathAnsible]/scripts/path_facts.py
    file: path={{ pathAnsibleLibrary }}/path_facts state=link src={{ pathAnsible }}/scripts/path_facts.py force=yes
    ignore_errors: yes

  - name: Enlazar /[pathAnsibleLibrary]/base_facts -> /[pathAnsible]/scripts/base_facts.py
    file: path={{ pathAnsibleLibrary }}/base_facts state=link src={{ pathAnsible }}/scripts/base_facts.py force=yes
    ignore_errors: yes
