---
# Configuración del servidor Web

- name: Copy web.conf to /etc/httpd/conf.d (Centos)
  template: src=etc/httpd/conf.d/web.conf.j2 dest=/etc/httpd/conf.d/web.conf owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" 

#- name: Copy web.conf to /etc/apache2/sites-available (Debian)
#  template: src=etc/apache2/sites-available/web.j2 dest=/etc/apache2/sites-available/web owner=root group=root mode=0644
#  when: ansible_os_family == "Debian"

#- name: Enable web in apache (Debian)
#  shell: a2ensite web 
#  notify: restart apache 
#  when: ansible_os_family == "Debian"

- name: Create Web directory
  file: path={{ webHtml }} state=directory owner={{ sshUserNodes }} group=root mode=0755

#- name: Add 'Defaults:sshUser !requiretty' in /etc/sudoers
#  lineinfile: 'name=/etc/sudoers state=present regexp="^Defaults:{{ sshUserNodes }} !requiretty" line="Defaults:{{ sshUserNodes }} !requiretty"'
#  when: sshUserNodes != "root" 

- name: Be sure rsync is installed (yum)
  yum: pkg=rsync state=installed
  when: ansible_pkg_mgr == "yum"

#- name: Be sure rsync is installed (apt)
#  apt: pkg=rsync state=installed update_cache=yes force=yes
#  when: ansible_pkg_mgr == "apt"

- name: Rsync web pages
  shell: rsync -arvce "ssh -o StrictHostKeyChecking=no" --delete --force {{ webFiles }}{{ webHtml }}/ {{ sshUserNodes }}@{{ hostWeb }}:{{ webHtml }}/ executable=/bin/bash
  delegate_to: "{{ hostAnsible }}"

- name: Permissions to Web directory
  file: path={{ webHtml }} state=directory owner={{ sshUserNodes }} group={{ userApache }} mode=0755

- name: Change owner/group to web files
  shell: chown -R {{ sshUserNodes }}.{{ userApache }} {{ webHtml }}/* 

- name: Change permissions to web files
  shell: chmod -R 640 {{ webHtml }}/*

- name: Change permissions to web directories
  #shell: chmod u+rwX,g+rX {{ webHtml }}/*
  shell: find {{ webHtml }} -type d -exec chmod 750 {} \;

- name: Copy db.php file (mysql config file)
  template: src=var/www/web/db.php.j2 dest={{ webHtml }}/db.php owner={{ sshUserNodes }} group={{ userApache }} mode=0640
