---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <epsms at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# Web Server configuration

- name: Copy web.conf to /etc/httpd/conf.d (Centos)
  template: src=etc/httpd/conf.d/web.conf.j2 dest=/etc/httpd/conf.d/web.conf owner=root group=root mode=0644
  notify: restart apache
  when: ansible_os_family == "RedHat" 

- name: Create Web directory
  file: path={{ webHtml }} state=directory owner={{ sshUserNodes }} group=root mode=0755

- name: Be sure rsync is installed (yum)
  yum: pkg=rsync state=installed
  when: ansible_pkg_mgr == "yum"

- name: Rsync web pages
  shell: rsync -arvce "ssh -o StrictHostKeyChecking=no" --delete --force {{ webFiles }}{{ webHtml }}/ {{ sshUserNodes }}@{{ hostWeb }}:{{ webHtml }}/ executable=/bin/bash
  delegate_to: "{{ hostAnsible }}"

- name: Permissions to Web directory
  file: path={{ webHtml }} state=directory owner={{ sshUserNodes }} group={{ userApache }} mode=0755

- name: Change owner/group to web files
  shell: chown -R {{ sshUserNodes }}.{{ userApache }} {{ webHtml }}/* 

- name: Change permissions to web files
  shell: chmod -R 640 {{ webHtml }}/*

- name: Change permissions to web directories
  #shell: chmod u+rwX,g+rX {{ webHtml }}/*
  shell: find {{ webHtml }} -type d -exec chmod 750 {} \;

- name: Copy db.php file (mysql config file)
  template: src=var/www/web/db.php.j2 dest={{ webHtml }}/db.php owner={{ sshUserNodes }} group={{ userApache }} mode=0640
