---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <epsms at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# Web Server installation (PhpMyAdmin)

- name: Be sure phpMyAdmin is installed (yum)
  yum: pkg={{ item }} enablerepo={{ labelEpel }} state=installed
  with_items: "{{ packagePhpMyAdmin }}"
  notify: restart apache
  when: ansible_pkg_mgr == "yum"

- name: Enlazar /etc/phpmyadmin -> /etc/phpMyAdmin (Centos)
  file: path=/etc/phpmyadmin state=link src=/etc/phpMyAdmin force=yes
  when: ansible_os_family == "RedHat" 

- name: Enlazar /usr/share/phpmyadmin -> /usr/share/phpMyAdmin (Centos)
  file: path=/usr/share/phpmyadmin state=link src=/usr/share/phpMyAdmin force=yes
  when: ansible_os_family == "RedHat"

- name: Allow iframes in /usr/share/phpMyAdmin/libraries/config.default.php file
  lineinfile: name=/usr/share/phpMyAdmin/libraries/config.default.php state=present regexp="^\$cfg\['AllowThirdPartyFraming'\]" line="$cfg['AllowThirdPartyFraming'] = true;"

- name: Copy phpmyadmin.conf to /etc/httpd/conf.d (Centos)
  template: src=etc/httpd/conf.d/phpmyadmin.conf.j2 dest=/etc/httpd/conf.d/phpMyAdmin.conf owner=root group=root mode=0644
  notify: restart apache
  when: ansible_os_family == "RedHat" 

- name: Unable PMA warnings in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['PmaNoRelation_DisableWarning'\] = TRUE;" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['PmaNoRelation_DisableWarning'] = TRUE;"

- name: Unable Suhosin warnings in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['SuhosinDisableWarning'\] = TRUE;" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['SuhosinDisableWarning'] = TRUE;"

- name: Unable controlpass in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['Servers'\]\[2\]\['controlpass'\] = '';" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['Servers'][2]['controlpass'] = '';"
  when: hostnameWeb == hostnameMysql

- name: Unable controluser in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['Servers'\]\[2\]\['controluser'\] = '';" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['Servers'][2]['controluser'] = '';"
  when: hostnameWeb == hostnameMysql

- name: Config Auth Type as HTTP in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['Servers'\]\[2\]\['auth_type'\] = 'http';" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['Servers'][2]['auth_type'] = 'http';"
  when: hostnameWeb == hostnameMysql

- name: Configure server as localhost in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['Servers'\]\[2\]\['host'\] = 'localhost';" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['Servers'][2]['host'] = 'localhost';"
  when: hostnameWeb == hostnameMysql

- name: Unable controlpass in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['Servers'\]\[1\]\['controlpass'\] = '';" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['Servers'][1]['controlpass'] = '';"

- name: Unable controluser in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['Servers'\]\[1\]\['controluser'\] = '';" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['Servers'][1]['controluser'] = '';"

- name: Config Auth Type as HTTP in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['Servers'\]\[1\]\['auth_type'\] = 'http';" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['Servers'][1]['auth_type'] = 'http';"

- name: Configure server as hostnameMysql in /etc/phpmyadmin/config.inc.php file
  lineinfile: name=/etc/phpmyadmin/config.inc.php state=present regexp="^\$cfg\['Servers'\]\[1\]\['host'\]" insertafter="^\$cfg\['SaveDir'\]" line="$cfg['Servers'][1]['host'] = '{{ hostnameMysql }}';"

