---
# Configuración del servidor Munin 

- name: Be sure mod_fcgid is installed (yum)
  yum: pkg=mod_fcgid enablerepo={{ labelEpel }} state=installed
  when: ansible_pkg_mgr == "yum"

#- name: Be sure libapache2-mod-fcgid is installed (apt)
#  apt: pkg=libapache2-mod-fcgid state=installed update_cache=yes force=yes
#  when: ansible_pkg_mgr == "apt"

#- name: Enable rewrite module in apache (Debian)
#  shell: a2enmod rewrite 
#  notify: restart apache
#  when: ansible_os_family == "Debian"

#- name: Enable fastCGI module in apache (Debian)
#  shell: a2enmod fcgid
#  notify: restart apache
#  when: ansible_os_family == "Debian"

- name: Copy munin.conf to /etc/munin
  template: src=etc/munin/munin.conf.j2 dest=/etc/munin/munin.conf owner=root group=root mode=0644

#- name: Copy apache.conf to /etc/munin (apt)
#  template: src=etc/munin/apache.conf.j2 dest=/etc/munin/apache.conf owner=root group=root mode=0644
#  notify: restart apache  
#  when: ansible_pkg_mgr == "apt"

- name: Copy munin.conf to /etc/httpd/conf.d (yum)
  template: src=etc/httpd/conf.d/munin.conf.j2 dest=/etc/httpd/conf.d/munin.conf owner=root group=root mode=0644
  notify: restart apache
  when: ansible_pkg_mgr == "yum"

- name: Enlazar /etc/munin/conf.d -> /etc/munin/munin-conf.d (RedHat)
  file: path=/etc/munin/munin-conf.d state=link src=/etc/munin/conf.d force=yes
  when: ansible_os_family == "RedHat"

#- name: Enlazar /etc/munin/conf.d -> /etc/munin/munin-conf.d (Debian)
#  file: path=/etc/munin/conf.d state=link src=/etc/munin/munin-conf.d force=yes
#  when: ansible_os_family == "Debian"

#- name: Enlazar path muninHtml/static -> /etc/munin/static (Debian)
#  file: path={{ muninHtml }}/static state=link src=/etc/munin/static force=yes
#  when: ansible_os_family == "Debian"

- name: Create cgi-tmp directory
  file: path=/var/lib/munin/cgi-tmp owner={{ userApache }} group={{ userApache }} state=directory mode=0755
