---
# Instalación del servidor Munin 

#- name: Install package python-pycurl, needed to add repository (apt)
#  apt: pkg=python-pycurl state=installed update_cache=yes force=yes
#  when: ansible_pkg_mgr == "apt"
  
#- name: Add Backports repository (needed to install Munin 2.X) (apt)
#  apt_repository: repo='deb http://backports.debian.org/debian-backports squeeze-backports main' state=present
#  when: ansible_pkg_mgr == "apt"

- name: Be sure munin is installed (yum)
  yum: pkg=munin enablerepo={{ labelEpel }} state=installed
  when: ansible_pkg_mgr == "yum"

#- name: Be sure munin is installed from backports (apt)
#  apt: pkg=munin default_release=squeeze-backports state=installed update_cache=yes force=yes
#  when: ansible_pkg_mgr == "apt"
